BMS_App/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
   #url(r'^$', 'BMS_App.views.index', name='index'),
   #url(r'^(?P<client_id>\d+)/view/$', 'BMS_App.views.client_view', name='client_view'),
   #url(r'^(?P<backup_id>\d+)/view/$', 'BMS_App.views.backup_view', name='backup_view'),
   )

BMS_Site/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from BMS_App.views import BackupEditForm,CustomUpdateView, BackupIndexList, CustomCreateView, GenericCreatedTimestampView
from BMS_App.models import Client, Backup, Contact, Restriction, Response
from BMS_Site import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'BMS_Site.views.home', name='home'),
    # url(r'^BMS_Site/', include('BMS_Site.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

     
##### Client URLs ###############
    # Index
      url(r'^clients/$', 'BMS_App.views.client_index', name='client_index'),
    # View
      url(r'^clients/(?P<pk>\d+)/view/$', 'BMS_App.views.client_view', name='client_view'),
    # Edit
      url(r'^clients/(?P<pk>\d+)/edit/$', 
        login_required(CustomUpdateView.as_view(
                        model=Client,
                        template_name="BMS_App/client_edit.html",
                        success_message="Client updated sucessfully")), 
        name='client_edit'),
      url(r'^clients/search/$', 'BMS_App.views.client_search', name='client_search'),


##### Backup URLs ###############
    # Index
      url(r'^backups/$', 'BMS_App.views.backup_index', name='backup_index'),
    # View
      url(r'^backups/(?P<pk>\d+)/view/$', 'BMS_App.views.backup_view', name='backup_view'),
    # Edit
      url(r'^backups/(?P<pk>\d+)/edit/$', 
        login_required(CustomUpdateView.as_view(
                        form_class=BackupEditForm,
                        model=Backup,
                        template_name="BMS_App/backup_edit.html",
                        success_message="Backup updated sucessfully")), 
        name='backup_edit'),
      url(r'^backups/([\w-]+)/$', BackupIndexList.as_view(), name='backup_index'),


##### Contact URLs ##############
    # Index
      url(r'^contacts/$', 'BMS_App.views.contact_index', name='contact_index'),
    # View
      url(r'^contacts/(?P<pk>\d+)/view/$', 'BMS_App.views.contact_view', name='contact_view'),
      url(r'^contacts/([\d+H|D|W|M|Y]+)/$', GenericCreatedTimestampView.as_view(), name='contact_index'),


##### Restriction URLs ##########
    # View
      url(r'^restrictions/(?P<pk>\d+)/view/$', 'BMS_App.views.restriction_view', name='restriction_view'),
    # Create  
      url(r'^restrictions/(?P<pk>\d+)/create/', 'BMS_App.views.restriction_create', name='restriction_create'),
    # Delete
      url(r'^restrictions/(?P<pk>\d+)/delete/$', 'BMS_App.views.restriction_delete', name='restriction_delete'),

##### Response URLs #############
    # Index
      url(r'^responses/$', 'BMS_App.views.response_index', name='response_index'),
    # View
      url(r'^responses/(?P<pk>\d+)/view/$', 'BMS_App.views.response_view', name='response_view'),
      url(r'^responses/([\d+H|D|W|M|Y]+)/$', GenericCreatedTimestampView.as_view(template_name="BMS_App/response_index.html", model=Response), name='response_index'),

##### Home Page #################
    url(r'^$', 'BMS_App.views.home', name='home'),
#################################

    # Login, logout
    url(r'^login/$',  'django.contrib.auth.views.login', 
        {'template_name' : 'login.html'}, name='tech_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page' : settings.LOGIN_REDIRECT_URL}, name='tech_logout'),

    # Password change
    url(r'^user/password/change/$', 'django.contrib.auth.views.password_change', 
        {'template_name' : 'password_change.html'}, name='password_change'),
    
    url(r'^user/password/change/done$', 'django.contrib.auth.views.password_change_done', 
        {'template_name' : 'password_change_done.html'}, name='password_change_done'),
    # Password reset
    url(r'^user/password/reset/$', 'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/user/password/reset/done/', 
          'template_name' : 'registration/password_reset.html'}, 
        name="password_reset"),
    url(r'^user/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    url(r'^user/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
          'django.contrib.auth.views.password_reset_confirm', 
          {'post_reset_redirect' : '/user/password/done/'}),
    url(r'^user/password/done/$','django.contrib.auth.views.password_reset_complete'),

    # Wiki
    url(r'^wiki/$', login_required(TemplateView.as_view(template_name="wiki.html")), name="wiki"),
)

BMS_App/models.py
from django.db import models
from django.forms import ModelForm
from django.core.urlresolvers import reverse
import os
from binascii import hexlify
import uuid

def _createId():
  return uuid.uuid1().hex #uuid.uuid4()#hexlify(os.urandom(16))

class Client(models.Model):
  name = models.CharField(max_length=60, db_index=True)
  created = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __unicode__(self):
    return self.name
  
  def get_absolute_url(self):
    return reverse('BMS_App.views.client_view', kwargs={'pk' : self.pk})

class Backup(models.Model):
  client = models.ForeignKey(Client)
  ticket_number = models.PositiveIntegerField(unique=True, db_index=True)
  backup_location = models.CharField(max_length=1024)
  size_in_megabytes = models.FloatField()
  # Create a random hash
  hash_id = models.CharField(max_length=32, unique=True, db_index=True, default=_createId)

  NEW = u'NEW'
  IN_PROGRESS = u'INP'
  CLOSED = u'CLO'
  ERROR = u'ERR'

  STATUS_CHOICES = (
      (NEW, u'New'),
      (IN_PROGRESS, u'In Progress'),
      (CLOSED, u'Closed'),
      (ERROR, u'Error'),
  )

  status = models.CharField(max_length=3, choices=STATUS_CHOICES, default=NEW)
  created = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated = models.DateTimeField(auto_now=True, auto_now_add=False)

  def __unicode__(self):
    return self.status + " " + self.backup_location

  def get_absolute_url(self):
    return reverse('BMS_App.views.backup_view', kwargs={'pk' : self.ticket_number})

class Contact(models.Model):
  backup = models.ForeignKey(Backup, db_index=True)
  created = models.DateTimeField(auto_now=False, auto_now_add=True)

  def __unicode__(self):
    return unicode(self.created)

class Response(models.Model):
  backup = models.ForeignKey(Backup, db_index=True)
  
  KEEP = 'KP'
  DEL  = 'DL'
  RESPONSE_CHOICES = (
      (KEEP, 'Keep data'),
      (DEL, 'Delete data'),
  )

  addedToWHDTicket = models.BooleanField(default=False)
  response = models.CharField(max_length=2, choices=RESPONSE_CHOICES, default=KEEP)
  justification = models.TextField(default="")
  created = models.DateTimeField(auto_now=False, auto_now_add=True)

  def __unicode__(self):
    return unicode(self.created)

class Restriction(models.Model):
  backup = models.ForeignKey(Backup, db_index=True)
  restrictContactsUntil = models.DateField(help_text="Input Format: MM/DD/YYYY")
  created = models.DateTimeField(auto_now=False, auto_now_add=True)
  updated = models.DateTimeField(auto_now=True, auto_now_add=False)

  def get_absolute_url(self):
    return reverse('BMS_App.views.restriction_view', kwargs={'pk' : self.pk})

class Email(models.Model):
  text = models.TextField();
  order = models.PositiveIntegerField()

  def __unicode__(self):
    return "Sent after " + unicode(self.order) + " contact(s). Text: " + unicode(self.text)


class IgnoreDirectory(models.Model):
  folderName = models.CharField(max_length=1024)
  
  def __unicode__(self):
    return unicode(self.folderName) 

BMS_App/templates/BMS_App/backup_snippet.html
	{# Different formatting based on status #}
	{% if backup.status == "NEW" %}
	<tr class="success">
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' backup.client.id %}">{{backup.client.name}}</a></td>
		<td><strong>Status:</strong></td>
		<td>{{backup.get_status_display }}</td>
	</tr>
	<tr class="success">
		<td><strong>Created:</strong></td>
		<td>{{ backup.created }}</td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{backup.ticket_number}}</td>
	</tr>
	<tr class="success">
		<td><strong>Updated:</strong></td>
		<td>{{ backup.updated }}</td>
		<td><a class="btn btn-primary btn-mini" href="{% url 'backup_view' backup.ticket_number %}">View Backup</a></td>
		<td><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{backup.ticket_number}}" target="_blank">WHD Ticket</a></td>
	</tr>
	{% elif backup.status == "INP" %}
	<tr class="warning">
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' backup.client.id %}">{{backup.client.name}}</a></td>
		<td><strong>Status:</strong></td>
		<td>{{backup.get_status_display }}</td>
	</tr>
	<tr class="warning">
		<td><strong>Created:</strong></td>
		<td>{{ backup.created }}</td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{backup.ticket_number}}</td>
	</tr>
	<tr class="warning">
		<td><strong>Updated:</strong></td>
		<td>{{ backup.updated }}</td>
		<td><a class="btn btn-primary btn-mini" href="{% url 'backup_view' backup.ticket_number %}">View Backup</a></td>
		<td><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{backup.ticket_number}}" target="_blank">WHD Ticket</a></td>
	</tr>
	{% elif backup.status == "CLO" %}
	<tr class="info">
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' backup.client.id %}">{{backup.client.name}}</a></td>
		<td><strong>Status:</strong></td>
		<td>{{backup.get_status_display }}</td>
	</tr>
	<tr class="info">
		<td><strong>Created:</strong></td>
		<td>{{ backup.created }}</td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{backup.ticket_number}}</td>
	</tr>
	<tr class="info">
		<td><strong>Updated:</strong></td>
		<td>{{ backup.updated }}</td>
		<td><a class="btn btn-primary btn-mini" href="{% url 'backup_view' backup.ticket_number %}">View Backup</a></td>
		<td><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{backup.ticket_number}}" target="_blank">View WHD Ticket</a></td>
        </tr>
	{% elif backup.status == "ERR" %}
	<tr class="error">
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' backup.client.id %}">{{backup.client.name}}</a></td>
		<td><strong>Status:</strong></td>
		<td>{{backup.get_status_display }}</td>
	</tr>
	<tr class="error">
		<td><strong>Created:</strong></td>
		<td>{{ backup.created }}</td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{backup.ticket_number}}</td>
	</tr>
	<tr class="error">
		<td><strong>Updated:</strong></td>
		<td>{{ backup.updated }}</td>
		<td><a class="btn btn-primary btn-mini" href="{% url 'backup_view' backup.ticket_number %}">View Backup</a></td>
		<td><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{backup.ticket_number}}" target="_blank">View WHD Ticket</a></td>
        </tr>
        {% else %}
        <tr> 
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' backup.client.id %}">{{backup.client.name}}</a></td>
		<td><strong>Status:</strong></td>
		<td>{{backup.get_status_display }}</td>
	</tr>
	<tr>
		<td><strong>Created:</strong></td>
		<td>{{ backup.created }}</td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{backup.ticket_number}}</td>
	</tr>
	<tr>
		<td><strong>Updated:</strong></td>
		<td>{{ backup.updated }}</td>
		<td><a class="btn btn-primary btn-mini" href="{% url 'backup_view' backup.ticket_number %}">View Backup</a></td>
		<td><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{backup.ticket_number}}" target="_blank">View WHD Ticket</a></td>
        </tr>

	{% endif %}

BMS_App/templates/BMS_App/client_index.html
{% extends "base.html" %}
{% block content %}

<div>
<h2>All Clients</h2>
	<table class="table table-bordered">
	<th style="text-align:center">Name</th>
	{% for client in clients_list%}
		{% if forloop.counter|divisibleby:2 %}
		<tr class="info">
		{% else %}
		<tr>
		{% endif %}
		<td><a href="{% url 'client_view' client.id%}">{{ client.name }}</a></td>
		</tr>
		
	{% endfor %}
	</table>
	{% include "BMS_App/pagination.html" with page=clients_list paginator=paginator%}
</div>

{% endblock %}

BMS_App/templates/BMS_App/client_search_results.html
{% extends "base.html" %}
{% block content %}

<div>
<h2>Search Results</h2>
	<table class="table table-bordered">
	<th style="text-align:center">Name</th>
	{% for client in clients_list%}
		{% if forloop.counter|divisibleby:2 %}
		<tr class="info">
		{% else %}
		<tr>
		{% endif %}
		
			<td><a href="{% url 'client_view' client.id%}">{{ client.name }}</a></td>
		</tr>
	{% endfor %}
	</table>
	{% include "BMS_App/pagination.html" with page=clients_list paginator=paginator%}
</div>

{% endblock %}

BMS_App/templates/BMS_App/client_snippet.html
<tr>
	<td><strong>Name:</strong></td>
	<td><a href="{% url 'client_view' client.id%}">{{ client.name }}</a></td>
</tr>
<tr>
	<td><strong>Created:</strong></td>
	<td>{{ client.created }}</td>
</tr>
<tr>
	<td><strong>Updated:</strong></td>
	<td>{{ client.updated }}</td>
</tr>

BMS_App/templates/BMS_App/client_view.html
{% extends "base.html" %}
{% block content %}
<h3>{{client.name}} <a href="{% url 'client_edit' client.id %}" class="btn btn-primary pull-right">Edit</a></h3>

<div class="firstColumn">
	<table class="table table-bordered">
		<tr><th colspan="2" style="text-align:center">Client</th><tr>
		{% include "BMS_App/client_snippet.html" %}
	</table>
</div>

<div class="secondColumn">
	<div class="accordion" id="accordion">	
		<div class="accordion-group">
			<div class="accordion-heading">
			  <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#backups" style="text-align:center;">Backups</a>
			</div>
			<div id="backups" class="accordion-body collapse in">
				<div class="accordion-inner">
						{% for backup in backups %}
							<table class="table table-bordered">
								{% include "BMS_App/backup_snippet.html" with backup=backup%}
							</table>
							{% if backups.count > 1%}
								<hr/>
							{% endif %}
						{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

BMS_App/templates/BMS_App/contact_index.html
{% extends "base.html" %}
{% block content %}

<div>
<h2>Contacts {%if startDate%} since {{ startDate }} {% endif %}</h2>
	<table class="table table-bordered">
	<th style="text-align:center">Date Received</th>
	<th style="text-align:center">Client</th>
	{% for contact in page_obj%}
		{% if forloop.counter|divisibleby:2 %}
			<tr class="info">
				<td><a href="{% url 'contact_view' contact.id%}">{{ contact.created }}</a></td>
				<td><a href="{% url 'client_view' contact.backup.client.id%}">{{ contact.backup.client.name }}</a></td>	
			</tr>
		{% else %}
			<tr>
				<td><a href="{% url 'contact_view' contact.id%}">{{ contact.created }}</a></td>
				<td><a href="{% url 'client_view' contact.backup.client.id%}">{{ contact.backup.client.name }}</a></td>	
			</tr>
		{% endif %}
	{% endfor %}
	</table>
	{% include "BMS_App/pagination.html" with page=page_obj paginator=page_obj.paginator%}
</div>

{% endblock %}

BMS_App/templates/BMS_App/contact_snippet.html

	<tr>
		<td><strong>ID:</strong></td>
		<td><a href="{% url 'contact_view' contact.id %}">{{contact.id}}</a></td>
	</tr>
	<tr>
		<td><strong>Sent:</strong></td>
		<td>{{ contact.created }}</td>
	</tr>

BMS_App/templates/BMS_App/form_snippet.html
{% csrf_token %}
{% if form.errors %}
<div class="alert alert-error"><h4>There was an error in the form.</h4></div>
{% endif %}

{% for field in form %}
	{% if field.errors %}
	<div class="control-group error">
	    <label class="control-label" for="{{ field.label}}">{{ field.label }}</label>
		<div class="controls">
		{{ field }}
		<span class="help-inline">{{ field.errors }}. {{ field.help_text }}</span>
		</div>
	</div>
	{% else %}
	<div class="control-group">
	    <label class="control-label" for="{{ field.label}}">{{ field.label }}</label>
		<div class="controls">
		{{ field }}
		<span class="help-inline">{{ field.help_text }}</span>
		</div>
    </div>
	{% endif %}
{% endfor %}



BMS_App/templates/BMS_App/index.html
{% extends "base.html" %}
{% block content %}
test
{% endblock %}

BMS_App/templates/BMS_App/response_index.html
{% extends "base.html" %}
{% block content %}

<div>
<h2>Responses {%if startDate%} since {{ startDate }} {% endif %}</h2>
	<table class="table table-hover table-bordered">
	{% for response in page_obj%}	
			{% include "BMS_App/response_snippet.html" with response=response %}
			<tr><td bgcolor=#6E6E6E colspan="4"></td></tr>
	{% endfor %}
	</table>
	{% include "BMS_App/pagination.html" with page=page_obj paginator=page_obj.paginator%}
</div>
{% endblock %}

BMS_App/templates/BMS_App/response_snippet.html
{% if response.response == "KP" %}
	<tr class="success">
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' response.backup.client.id %}">{{response.backup.client.name}}</a></td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{ response.backup.ticket_number }}</td>
	</tr>
	<tr class="success">
		<td><strong>Response:</strong></td>
		<td>{{response.get_response_display}}</td>
		<td colspan=2 style="text-align:center" ><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{response.backup.ticket_number}}">View WHD Ticket</a></td>
	</tr>
	<tr class="success">
		<td><strong>Received:</strong></td>
		<td>{{ response.created }}</td>
		<td colspan=2 style="text-align:center" ><a class="btn btn-primary btn-mini" href="{% url 'backup_view' response.backup.ticket_number %}">View Backup</a></td>	
	</tr>
	{% if response.justification %}
		<tr class="success">
			<td><strong>Justification:</strong></td>
			<td colspan=3>{{response.justification}}</td>	
		</tr>
	{% endif %}
{% else %}
	<tr class="error">
		<td><strong>Client:</strong></td>
		<td><a href="{% url 'client_view' response.backup.client.id %}">{{response.backup.client.name}}</a></td>
		<td><strong>Ticket Number:</strong></td>
		<td>{{ response.backup.ticket_number }}</td>
	</tr>
	<tr class="error">
		<td><strong>Response:</strong></td>
		<td>{{response.get_response_display}}</td>
		<td colspan=2 style="text-align:center" ><a class="btn btn-primary btn-mini" href="https://helpdesk.wustl.edu/helpdesk/WebObjects/Helpdesk.woa/wa/TicketActions/view?ticket={{response.backup.ticket_number}}">View WHD Ticket</a></td>
	</tr>
	<tr class="error">
		<td><strong>Received:</strong></td>
		<td>{{ response.created }}</td>
		<td colspan=2 style="text-align:center" ><a class="btn btn-primary btn-mini" href="{% url 'backup_view' response.backup.ticket_number %}">View Backup</a></td>	
	</tr>
	{% if response.justification %}
		<tr class="error">
			<td><strong>Justification:</strong></td>
			<td colspan=3>{{response.justification}}</td>	
		</tr>
	{% endif %}
{% endif %}





BMS_App/templates/BMS_App/restriction_create.html
{% extends "base.html" %}
{% block content %}

<h3>Create restriction</h3>
<form class="form-horizontal" action="{% url 'restriction_create' backup.id%}" method="post">
	{% include "BMS_App/form_snippet.html" %}
	<div class="controls"><input type="submit" value="Add Restriction" /></div>
</form>
{% endblock %}

BMS_App/templates/BMS_App/restriction_snippet.html
	<tr>
		<td><strong>ID:</strong></td>
		<td><a href="{% url 'restriction_view' restriction.id %}">{{restriction.id}}</a></td>
	</tr>
	<tr>
		<td><strong>Backup ID:</strong></td>
		<td><a href="{% url 'backup_view' restriction.backup.id %}">{{ restriction.backup.id }}</td>
	</tr>
	<tr>
		<td><strong>Don't Email Until:</strong></td>
		<td>{{ restriction.restrictContactsUntil }}</td>
	</tr>
	<tr>
		<td><strong>Created:</strong></td>
		<td>{{ restriction.created }}</td>
	</tr>

BMS_App/templates/BMS_App/restriction_view.html
{% extends "base.html" %}
{% block content %}
<h3>Restriction: {{ restriction.id}}</h3>
<div class="firstColumn">
<table class="table table-bordered">
	{% include "BMS_App/restriction_snippet.html" with restriction=restriction %}
</table>
</div>
{% endblock %}